# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_in_vscode_template',
                'doc_host': 'https://ynab.github.io',
                'git_url': 'https://github.com/ynab/nbdev_in_vscode_template',
                'lib_path': 'nbdev_in_vscode_template'},
  'syms': { 'nbdev_in_vscode_template.core': { 'nbdev_in_vscode_template.core.add_one': ( 'core.html#add_one',
                                                                                          'nbdev_in_vscode_template/core.py'),
                                               'nbdev_in_vscode_template.core.say_hello': ( 'core.html#say_hello',
                                                                                            'nbdev_in_vscode_template/core.py')}}}
