# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'add_one']

# %% ../nbs/00_core.ipynb 3
def say_hello(to):
    "Say hello to somebody"
    return f"Hello {to}!"

# %% ../nbs/00_core.ipynb 5
def add_one(x):
    return x + 1
